"""code added in prodcut category

Revision ID: 3c87bb9e808b
Revises: 90b452226718
Create Date: 2025-05-18 21:56:27.477563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c87bb9e808b'
down_revision: Union[str, None] = '90b452226718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productcategory', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.create_unique_constraint(None, 'productcategory', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productcategory', type_='unique')
    op.drop_column('productcategory', 'code')
    # ### end Alembic commands ###
